layout_spectrum: 0
color:
  saturation: 0.2711357
  lightness: 0.5213316
  brandStrength: 0.8113982
  rhythmicContrast: 0.9098933
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.7785011
name: 'Ponders & Banters '
